# Generated by GitHub Copilot
import json

from channels.db import database_sync_to_async
from channels.generic.websocket import AsyncWebsocketConsumer
from django.utils import timezone

from blog.models import Post

from .models import GlobalChatMessage, PostChatMessage


class GlobalChatConsumer(AsyncWebsocketConsumer):
    """WebSocket consumer for the global blog chat room."""

    async def connect(self):
        """Accept authenticated users and join the global room group."""
        if self.scope['user'].is_anonymous:
            await self.close(code=4401)
            return

        self.room_group_name = 'global_blog_chat'
        await self.channel_layer.group_add(self.room_group_name, self.channel_name)
        await self.accept()

    async def disconnect(self, close_code):
        """Leave the global room group on websocket disconnect."""
        await self.channel_layer.group_discard(self.room_group_name, self.channel_name)

    async def receive(self, text_data=None, bytes_data=None):
        """Validate, persist, and broadcast one global chat message."""
        if not text_data:
            return

        try:
            payload = json.loads(text_data)
        except json.JSONDecodeError:
            return

        message = (payload.get('message') or '').strip()
        if not message:
            return
        message = message[:1000]

        created_at = await self._save_message(message)
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'username': self.scope['user'].username,
                'message': message,
                'created_at': timezone.localtime(created_at).strftime('%Y-%m-%d %H:%M:%S'),
            },
        )

    async def chat_message(self, event):
        """Send one serialized chat payload to the frontend."""
        await self.send(
            text_data=json.dumps(
                {
                    'type': 'chat.message',
                    'username': event['username'],
                    'message': event['message'],
                    'created_at': event['created_at'],
                }
            )
        )

    @database_sync_to_async
    def _save_message(self, message):
        """Create and return one global chat message record timestamp."""
        record = GlobalChatMessage.objects.create(user=self.scope['user'], message=message)
        return record.created_at


class PostChatConsumer(AsyncWebsocketConsumer):
    """WebSocket consumer for post-specific chat rooms."""

    async def connect(self):
        """Accept authenticated users and join one post chat room."""
        if self.scope['user'].is_anonymous:
            await self.close(code=4401)
            return

        self.slug = self.scope['url_route']['kwargs']['slug']
        if not await self._post_exists(self.slug):
            await self.close(code=4404)
            return

        self.room_group_name = f'post_blog_chat_{self.slug}'
        await self.channel_layer.group_add(self.room_group_name, self.channel_name)
        await self.accept()

    async def disconnect(self, close_code):
        """Leave the post room group on websocket disconnect."""
        await self.channel_layer.group_discard(self.room_group_name, self.channel_name)

    async def receive(self, text_data=None, bytes_data=None):
        """Validate, persist, and broadcast one post chat message."""
        if not text_data:
            return

        try:
            payload = json.loads(text_data)
        except json.JSONDecodeError:
            return

        message = (payload.get('message') or '').strip()
        if not message:
            return
        message = message[:1000]

        created_at = await self._save_message(self.slug, message)
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'username': self.scope['user'].username,
                'message': message,
                'created_at': timezone.localtime(created_at).strftime('%Y-%m-%d %H:%M:%S'),
            },
        )

    async def chat_message(self, event):
        """Send one serialized chat payload to the frontend."""
        await self.send(
            text_data=json.dumps(
                {
                    'type': 'chat.message',
                    'username': event['username'],
                    'message': event['message'],
                    'created_at': event['created_at'],
                }
            )
        )

    @database_sync_to_async
    def _post_exists(self, slug):
        """Return whether the post slug exists before room join."""
        return Post.objects.filter(slug=slug).exists()

    @database_sync_to_async
    def _save_message(self, slug, message):
        """Create and return one post chat message record timestamp."""
        post = Post.objects.get(slug=slug)
        record = PostChatMessage.objects.create(post=post, user=self.scope['user'], message=message)
        return record.created_at
