from django import forms

from .models import Post


# Generated by GitHub Copilot
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "publish_date"]
        widgets = {
            "title": forms.TextInput(attrs={"maxlength": 200}),
            "content": forms.Textarea(attrs={"rows": 14}),
            "publish_date": forms.DateInput(attrs={"type": "date"}),
        }
