from django.contrib.auth.models import Permission, User
from django.test import TestCase
from django.urls import reverse

from .models import Post


# Generated by GitHub Copilot
class PostCrudViewTests(TestCase):
	def setUp(self):
		self.user = User.objects.create_user(username="editor", password="secret123")
		self.user.user_permissions.add(Permission.objects.get(codename="change_post"))
		self.user.user_permissions.add(Permission.objects.get(codename="add_post"))
		self.user.user_permissions.add(Permission.objects.get(codename="delete_post"))
		self.post = Post.objects.create(
			title="Original title",
			content="Original content",
			slug="original-title",
		)

	def test_create_view_creates_and_persists_post(self):
		self.client.login(username="editor", password="secret123")

		response = self.client.post(
			reverse("post-create-page"),
			{
				"title": "New browser post",
				"content": "Created from the browser.",
				"publish_date": "2026-05-21",
			},
		)

		self.assertRedirects(response, reverse("post-details-page", args=["new-browser-post"]))
		self.assertTrue(Post.objects.filter(slug="new-browser-post", title="New browser post").exists())

	def test_edit_view_renders_for_user_with_permission(self):
		self.client.login(username="editor", password="secret123")

		response = self.client.get(reverse("post-edit-page", args=[self.post.slug]))

		self.assertEqual(response.status_code, 200)
		self.assertContains(response, "Save changes")

	def test_post_request_updates_and_persists_post(self):
		self.client.login(username="editor", password="secret123")

		response = self.client.post(
			reverse("post-edit-page", args=[self.post.slug]),
			{
				"title": "Edited title",
				"content": "Edited content saved from the browser.",
				"publish_date": "2026-05-21",
			},
		)

		self.assertRedirects(response, reverse("post-details-page", args=["edited-title"]))

		self.post.refresh_from_db()
		self.assertEqual(self.post.title, "Edited title")
		self.assertEqual(self.post.slug, "edited-title")
		self.assertEqual(self.post.content, "Edited content saved from the browser.")

	def test_delete_request_removes_post(self):
		self.client.login(username="editor", password="secret123")

		response = self.client.post(reverse("post-delete-page", args=[self.post.slug]))

		self.assertRedirects(response, reverse("starting-page"))
		self.assertFalse(Post.objects.filter(pk=self.post.pk).exists())
