import calendar
from datetime import timedelta
from .models import AboutPage
from .models import GlobalChatMessage
from .models import Post
from .models import PostChatMessage
from .forms import PostForm
from .blog_extras import save_post_from_form
from django.shortcuts import get_object_or_404, render , redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.utils import timezone
from django.http import JsonResponse
from django.views.decorators.http import require_POST

from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseForbidden


# Create your views here.


# Generated by GitHub Copilot
def _parse_month_year_params(request):
    """Parse and validate month/year query params with safe defaults."""
    today = timezone.localdate()
    selected_month = today.month
    selected_year = today.year

    month_query = request.GET.get("month")
    year_query = request.GET.get("year")

    try:
        if month_query is not None:
            selected_month = max(1, min(12, int(month_query)))
        if year_query is not None:
            selected_year = max(1900, min(2100, int(year_query)))
    except (TypeError, ValueError):
        selected_month = today.month
        selected_year = today.year

    return selected_month, selected_year, today


# Generated by GitHub Copilot
def _build_calendar_weeks(selected_month, selected_year, today):
    """Build a 6-week calendar matrix and attach posts to each day."""
    calendar_matrix = calendar.Calendar(firstweekday=0).monthdatescalendar(selected_year, selected_month)
    while len(calendar_matrix) < 6:
        previous_week = calendar_matrix[-1]
        first_day = previous_week[-1] + timedelta(days=1)
        calendar_matrix.append([first_day + timedelta(days=offset) for offset in range(7)])

    dated_posts = Post.objects.exclude(publish_date__isnull=True).order_by("-publish_date", "-id")
    posts_by_date = {}
    for post in dated_posts:
        posts_by_date.setdefault(post.publish_date, []).append(post)

    calendar_weeks = []
    for week in calendar_matrix:
        week_days = []
        for day in week:
            week_days.append(
                {
                    "date": day,
                    "is_current_month": day.month == selected_month,
                    "is_today": day == today,
                    "posts": posts_by_date.get(day, []),
                }
            )
        calendar_weeks.append(week_days)

    return calendar_weeks


# Generated by GitHub Copilot
def custom_logout(request):
    """Custom logout view that redirects to login page"""
    logout(request)
    return redirect('login')

def starting_page(request):
    # Generated by GitHub Copilot
    if request.method == "POST":
        username = request.POST.get("username")
        print(username)

    selected_month, selected_year, today = _parse_month_year_params(request)

    posts = Post.objects.all().order_by("-publish_date", "-id")
    calendar_weeks = _build_calendar_weeks(selected_month, selected_year, today)

    prev_month = selected_month - 1
    prev_year = selected_year
    if prev_month == 0:
        prev_month = 12
        prev_year -= 1

    next_month = selected_month + 1
    next_year = selected_year
    if next_month == 13:
        next_month = 1
        next_year += 1

    about_pages = AboutPage.objects.all().order_by("-id")

    return render(request, "blog/index.html", {
        "about_pages": about_pages,
        "posts": posts,
        "calendar_weeks": calendar_weeks,
        "calendar_month_name": calendar.month_name[selected_month],
        "calendar_month": selected_month,
        "calendar_year": selected_year,
        "calendar_prev_month": prev_month,
        "calendar_prev_year": prev_year,
        "calendar_next_month": next_month,
        "calendar_next_year": next_year,
        "calendar_year_options": range(selected_year - 4, selected_year + 5),
        "calendar_today_month": today.month,
        "calendar_today_year": today.year,
    })

@login_required
def restricted(request):
    return render(request, "blog/restricted.html")



def about(request):
    return render(request, "blog/about.html")



@permission_required("blog.change_aboutpage", raise_exception=True)
def about_edit(request):
    return render(request, "blog/about_edit.html")

def posts(request):
    pass

def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)

    return render(request, "blog/post-detail.html", {
        "post": post
    })


# Generated by GitHub Copilot
@login_required
@permission_required("blog.add_post", raise_exception=True)
def post_create(request):
    """Create one post from the browser and persist it to the local database."""
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = save_post_from_form(form)
            return redirect("post-details-page", slug=post.slug)
    else:
        form = PostForm()

    return render(request, "blog/post_edit.html", {
        "form": form,
        "post": None,
        "page_heading": "Create post",
        "page_description": "Add a new blog post in the browser and save it directly into the local database.",
        "submit_label": "Create post",
    })


# Generated by GitHub Copilot
@login_required
@permission_required("blog.change_post", raise_exception=True)
def post_edit(request, slug):
    """Edit one post through the browser and persist the validated changes."""
    post = get_object_or_404(Post, slug=slug)
    original_title = post.title
    original_slug = post.slug

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            updated_post = save_post_from_form(
                form,
                original_title=original_title,
                original_slug=original_slug,
            )
            return redirect("post-details-page", slug=updated_post.slug)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/post_edit.html", {
        "post": post,
        "form": form,
        "page_heading": "Edit post",
        "page_description": "Changes saved here are written to the local database and shown on the public post page immediately.",
        "submit_label": "Save changes",
    })


# Generated by GitHub Copilot
@login_required
@permission_required("blog.delete_post", raise_exception=True)
@require_POST
def post_delete(request, slug):
    """Delete one post through the browser and redirect back to the blog list."""
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    return redirect("starting-page")


# Generated by GitHub Copilot
@login_required
def global_chat_messages(request):
    """Return the most recent global chat messages for the widget bootstrap."""
    messages = (
        GlobalChatMessage.objects.select_related("user")
        .order_by("-created_at", "-id")[:50]
    )
    serialized = [
        {
            "username": row.user.username,
            "message": row.message,
            "created_at": timezone.localtime(row.created_at).strftime("%Y-%m-%d %H:%M:%S"),
        }
        for row in reversed(list(messages))
    ]
    return JsonResponse({"messages": serialized})


# Generated by GitHub Copilot
@login_required
def post_chat_messages(request, slug):
    """Return the most recent chat messages for one post room."""
    post = get_object_or_404(Post, slug=slug)
    messages = (
        PostChatMessage.objects.filter(post=post)
        .select_related("user")
        .order_by("-created_at", "-id")[:50]
    )
    serialized = [
        {
            "username": row.user.username,
            "message": row.message,
            "created_at": timezone.localtime(row.created_at).strftime("%Y-%m-%d %H:%M:%S"),
        }
        for row in reversed(list(messages))
    ]
    return JsonResponse({"messages": serialized})

# Generated by GitHub Copilot
def calendar_data_json(request):
    """Returns calendar data for a given month as JSON (no page reload)."""
    month, year, today = _parse_month_year_params(request)
    calendar_weeks = _build_calendar_weeks(month, year, today)

    weeks = []
    for week in calendar_weeks:
        week_days = []
        for day in week:
            day_posts = day["posts"]
            week_days.append({
                "date": day["date"].isoformat(),
                "day": day["date"].day,
                "is_current_month": day["is_current_month"],
                "is_today": day["is_today"],
                "has_posts": len(day_posts) > 0,
                "posts": [{"title": p.title, "slug": p.slug} for p in day_posts],
            })
        weeks.append(week_days)
    
    return JsonResponse({
        "month_name": calendar.month_name[month],
        "month": month,
        "year": year,
        "weeks": weeks,
    })

# Generated by GitHub Copilot
def calendar_grid_html(request):
    """Returns calendar grid HTML for AJAX updates (no page reload)."""
    month, year, today = _parse_month_year_params(request)
    calendar_weeks = _build_calendar_weeks(month, year, today)
    
    return render(request, "blog/calendar_grid.html", {
        "calendar_weeks": calendar_weeks,
    })
