# Generated by GitHub Copilot
from django.apps import AppConfig


class EmojiReactionsConfig(AppConfig):
    """App config for the emoji reactions feature."""
    default_auto_field = "django.db.models.BigAutoField"
    name = "emoji_reactions"
