# Generated by GitHub Copilot
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# Emoji options shown in the reaction picker popup
AVAILABLE_EMOJIS = ["👍", "❤️", "😂", "😮", "😢", "🔥", "🎉", "👏"]


class EmojiReaction(models.Model):
    """
    Stores a reaction count per emoji per content object.
    Uses Django's ContentTypes framework for a generic relation to any model.
    """
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    emoji = models.CharField(max_length=10)
    count = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ("content_type", "object_id", "emoji")

    def __str__(self):
        return f"{self.emoji} × {self.count} on {self.content_type} #{self.object_id}"

    @classmethod
    def button_payload_for(cls, obj):
        """Return a list of emoji button dicts (emoji, count) for a given object."""
        content_type = ContentType.objects.get_for_model(obj, for_concrete_model=False)
        reaction_counts = {
            r.emoji: r.count
            for r in cls.objects.filter(content_type=content_type, object_id=obj.pk)
        }
        return [
            {"emoji": emoji, "count": reaction_counts.get(emoji, 0)}
            for emoji in AVAILABLE_EMOJIS
        ]
