# Generated by GitHub Copilot
from django.db import models as django_models
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.contrib.contenttypes.models import ContentType
from django.utils.http import url_has_allowed_host_and_scheme

from .models import EmojiReaction, AVAILABLE_EMOJIS

_SESSION_KEY = "emoji_reactions"


def build_object_session_key(content_type_pk, object_pk):
    """Build a unique session dict key for a given content type + object pair."""
    return f"{content_type_pk}:{object_pk}"


def get_session_reaction_state(request, session_key):
    """
    Return (reaction_map, state) from the session for the given session_key.
    reaction_map is the full dict; state is the per-object sub-dict.
    """
    reaction_map = request.session.get(_SESSION_KEY, {})
    state = reaction_map.get(session_key, {})
    return reaction_map, state


@require_POST
def react(request):
    """
    Handle an emoji reaction POST.
    Toggles the reaction for the current browser session and updates the count.
    Validates all inputs and redirects back to next_url.
    """
    content_type_id = request.POST.get("content_type_id")
    object_id = request.POST.get("object_id")
    emoji = request.POST.get("emoji", "")
    next_url = request.POST.get("next_url", "/")

    # Prevent open-redirect: only allow same-host URLs
    if not url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}):
        next_url = "/"

    # Validate emoji against allow-list
    if emoji not in AVAILABLE_EMOJIS:
        return redirect(next_url)

    # Validate and resolve the content type
    try:
        content_type_id = int(content_type_id)
        object_id = int(object_id)
        ContentType.objects.get(pk=content_type_id)
    except (TypeError, ValueError, ContentType.DoesNotExist):
        return redirect(next_url)

    session_key = build_object_session_key(content_type_id, object_id)
    reaction_map, state = get_session_reaction_state(request, session_key)
    previous_reaction = state.get("reaction")

    if previous_reaction == emoji:
        # Toggle the same emoji off
        EmojiReaction.objects.filter(
            content_type_id=content_type_id, object_id=object_id, emoji=emoji
        ).update(count=django_models.F("count") - 1)
        state = {}
    else:
        # Remove the old reaction if any
        if previous_reaction:
            EmojiReaction.objects.filter(
                content_type_id=content_type_id, object_id=object_id, emoji=previous_reaction
            ).update(count=django_models.F("count") - 1)

        # Increment (or create) the new reaction
        EmojiReaction.objects.get_or_create(
            content_type_id=content_type_id,
            object_id=object_id,
            emoji=emoji,
            defaults={"count": 0},
        )
        EmojiReaction.objects.filter(
            content_type_id=content_type_id, object_id=object_id, emoji=emoji
        ).update(count=django_models.F("count") + 1)

        state = {"reaction": emoji}

    reaction_map[session_key] = state
    request.session[_SESSION_KEY] = reaction_map
    request.session.modified = True
    return redirect(next_url)
